#ifndef SRC_PROJECT_STYLESHEET_H_
#define SRC_PROJECT_STYLESHEET_H_

#include <QString>

static QString StyleSheetBackSpace = "QPushButton { "
									"margin:5px;"
									"color: black; "
									"background-color: #9477af; "
									"border: none; "
									"font: 17pt 'Microsoft YaHei UI Light'; "
									"outline: none; "
									"} "
									"QPushButton:hover { "
									"background-color: #9477af; "
									"border-style: solid; "
									"border-width: 3px; "
									"border-color: #E6E6E6; "
									"} "
									"QPushButton:pressed { "
									"background-color: #A4A4A4; "
									"border-style: solid; "
									"border-width: 3px; "
									"border-color: #E6E6E6; "
									"}";

static QString StyleSheetCalcsButton = "QPushButton {"
										"margin: 5px;"
										"font: 12pt 'Microsoft YaHei UI Light'; "
										"padding: 0px 0px 0px 5px;"
										"color: black;"
										"border-radius: 5px;"
										"background-color: grey;"
										"}"
										"QPushButton:hover { "
										"background-color: #9477af; "
										"border-style: solid; "
										"border-width: 3px; "
										"border-color: #E6E6E6; "
										"} "
										"QPushButton:pressed { "
										"background-color: #A4A4A4; "
										"border-style: solid; "
										"border-width: 3px; "
										"border-color: #E6E6E6; "
										"}";

static QString StyleSheetGraphButton = "QPushButton {"
										"font-size: 15px;"
										"margin: 5px;"
										"color: black;"
										"background-color: green;"
										"border: 0;"
										"border-radius: 5px;"
										"}"
										"QPushButton:hover { "
										"background-color: #9477af; "
										"border-style: solid; "
										"border-width: 3px; "
										"border-color: #E6E6E6; "
										"} "
										"QPushButton:pressed { "
										"background-color: #A4A4A4; "
										"border-style: solid; "
										"border-width: 3px; "
										"border-color: #E6E6E6; "
										"}";

static QString StyleSheetLine = "QLineEdit {"
								"background-color:#195DA9;"
								"font-size:30px;"
								"padding:12px;"
								"border:none;"
								"outline:0;"
								"color:#fff;"
								"font-weight:300;"
								"}";

static QString StyleSheetNumbers = "QPushButton {"
									"margin:5px;"
									"background-color:#FAFAFA;"
									"color:#949DA8;"
									"width:60px;"
									"height:60px;"
									"font-size:20px;"
									"border:0;"
									"border-radius:5px;"
									"} "
									"QPushButton:hover {"
									"background:#9c89f6;"
									"color:white;"
									"}";

static QString StyleSheetSigns = "QPushButton {"
								"margin:5px;"
								"background-color:#F1F8FE;"
								"color:#195DA9;"
								"width:60px;"
								"height:60px;"
								"font-size:20px;"
								"border:0;"
								"border-radius:5px;"
								"} "
								"QPushButton:hover { "
								"background-color: #2ECCFA; "
								"border-style: solid; "
								"border-width: 3px; "
								"border-color: #58D3F7; "
								"} "
								"QPushButton:pressed { "
								"background-color: #81DAF5; "
								"border-style: solid; "
								"border-width: 3px; "
								"border-color: #A9E2F3; "
								"}";

static QString StyleSheetSpecSigns = "QPushButton {"
									"margin:5px;"
									"background-color:#FAFAFA;"
									"color:#949DA8;"
									"width:60px;"
									"height:60px;"
									"font-size:20px;"
									"border:0;"
									"border-radius:5px;"
									"} "
									"QPushButton:hover {"
									"background:#9c89f6;"
									"color:white;"
									"}";

static QString StyleSheetSpecRoot = "QPushButton {"
									"max-width: 77px; "
									"color: black; "
									"background-color: #E6E6E6; "
									"border: none; "
									"font: 16pt 'Microsoft YaHei UI Light'; "
									"outline: none; "
									"} "
									"QPushButton:hover { "
									"background-color: #D8D8D8; "
									"border-style: solid; "
									"border-width: 3px; "
									"border-color: #E6E6E6; "
									"} "
									"QPushButton:pressed { "
									"background-color: #A4A4A4; "
									"border-style: solid; "
									"border-width: 3px; "
									"border-color: #E6E6E6; "
									"}";

#endif  // SRC_PROJECT_STYLESHEET_H_
